blank_issues_enabled: false
contact_links:
  - name: Setup Help
    url: https://hivemindrobotics.net/team#contact
    about: Help with setting up the Portfolio utility
  - name: FTC Discord
    url: https://discord.gg/first-tech-challenge
    about: Speak with us directly in the FTC Discord! Just ping @isitpolar
