name: Removal Request
description: Request a portfolio be added to our evergrowing database!
title: 'Portfolio Removal/Modification » '
labels: ['modification']
body:
  - type: markdown
    attributes:
      value: |
        Please make sure to include all the required fields to get your portfolio removed.
  - type: input
    id: team-name
    attributes:
      label: 'Team Name'
      description: What is your team's name?
      placeholder: Hivemind
    validations:
      required: true
  - type: input
    id: team-number
    attributes:
      label: 'Team Number'
      description: What is your team's number?
      placeholder: '23396'
    validations:
      required: true
  - type: input
    id: team-region
    attributes:
      label: 'Team Region'
      description: What is your team's number?
      placeholder: Tennessee
    validations:
      required: true
  - type: dropdown
    id: field
    attributes:
      label: 'Reason of request'
      description: What is this request's reasoning
      options:
        - Removal
        - Replacement
        - Modification
  - type: input
    id: download-portfolio
    attributes:
      label: 'Replacement: Download Portfolio'
      description: Please provide a direct download link through dropbox or google drive.
      placeholder: Your drive link
    validations:
      required: false
  - type: input
    id: removal-reason
    attributes:
      label: 'Reason for Removal or Modification'
      description: Why do you want your team's portfolio removed or modified?
      placeholder: I want this portfolio removed or modified because...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: 'Code of Conduct'
      description: |
        By submitting this issue, you confirm that you are a member of this team or a mentor/coach of this team, who is requesting to remove it's portfolio from this open-source database.
      options:
        - label: I agree to follow this project's Code of Conduct. I am a member, coach, or mentor of this team and I am requesting the removal or modification of this form.
          required: true
